mpc_controller:
  robot:
    name: "s500_uam"
    urdf: "models/urdf/s500_uam_simple.urdf"
    follow: "config/yaml/multicopter/s500.yaml"

  integration_method: "IntegratedActionModelEuler"
  knots: 20
  solver: "SolverSbFDDP"
  iters: 10
  dt: 50

  rail_weight: 1
  # rail_activation_weights: [20, 20, 50, 1, 1, 1, 10, 100, 1, 1, 1, 0, 0, 0, 0.0, 0.0]   # need to add some weights for arm joints
  # rail_activation_weights: [100, 100, 100, 5, 5, 5, 20, 50, 1, 1, 1, 1, 1, 1, 1, 1]   # need to add some weights for arm joints
  rail_activation_weights: [100, 100, 100, 1, 1, 1, 100, 100, 1, 1, 1, 1, 1, 1, 1, 1]
  # rail_activation_weights: [0, 0, 0, 0, 0, 0, 10000, 10000, 0, 0, 0, 0, 0, 0, 1, 1]   # need to add some weights for arm joints
  rail_control_weight: 0
  
  control_reference: [4.94, 4.94, 4.94, 4.94, 0, 0]

  # State limits parameters for rail-mpc
  rail_state_limits_weight: 0
  rail_state_limits_act_weights: [0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  rail_state_limits_u_bound: [0, 0, 0, 1, 1, 0, 1.5, 1.5, 2, 2, 1, 1, 1, 1, 3, 3]
  rail_state_limits_l_bound: [0, 0, 0, -1, -1, 0, -1.5, -1.5, -2, -2, -1, -1, -1, -1, -3, -3]
