trajectory:
  robot:
    name: "s500"
    urdf: "models/urdf/s500_simple.urdf"
    follow: "config/yaml/multicopter/s500.yaml"

  initial_state: [0, 0, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

  stages:
    - name: "nav_wp1"
      duration: 2000 #ms
      transition: true
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 1e-2
          reference: [2, 0, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]        

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 100
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1]
          l_bound: [0, 0, 0, 0, 0, 0, -2, -2, -1, -1, -1, -1]

    - name: "wp_1"
      duration: 0 #ms
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 100
          reference: [2, 0, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]


    - name: "nav_wp2"
      duration: 2000 #ms
      transition: true
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 1e-2
          reference: [2, 2, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 100
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1]
          l_bound: [0, 0, 0, 0, 0, 0, -2, -2, -1, -1, -1, -1]

    - name: "wp_2"
      duration: 0 #ms
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 100
          reference: [2, 2, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

    - name: "nav_wp3"
      duration: 2000 #ms
      transition: true
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 1e-2
          reference: [0, 2, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 100
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1]
          l_bound: [0, 0, 0, 0, 0, 0, -2, -2, -1, -1, -1, -1]

    - name: "wp_3"
      duration: 0 #ms
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 100
          reference: [0, 2, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]
          

    - name: "nav_wp4"
      duration: 2000 #ms
      transition: true
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 1e-2
          reference: [0, 0, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 100
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1]
          l_bound: [0, 0, 0, 0, 0, 0, -2, -2, -1, -1, -1, -1]

    - name: "wp_4"
      duration: 0 #ms
      costs:
        - name: "reg_state"
          type: "ResidualModelState"
          weight: 20
          reference: [0, 0, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

